version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/monitor
    ports:
      - "8000:8000"
    links:
      - redis
